title:    Anna Duan  # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/annaduan/">LinkedIn</a> | <a href="https://medium.com/@brickandpave">Blog</a> | <a href="https://annaduan09.github.io/anna-duan-portfolio/file/ADuan_Resume_June_2021">Resume</a>
  <br><br>  
  Third year undergraduate student majoring in Urban Studies with a concentration in Spatial Analytics @ University of Pennsylvania 
  <br><br>
  I enjoy spatial data, transportation research, and powerlifting.
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
